CPATH=/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
CFLAGS=-Wall -o -Og -g -v -std=c99

gisutil:
	touch gisutil.c                 # touch to make setup.py rebuild
	sudo python setup.py install
